### ISSUE TITLE
UED Landing Page: If we can get the custom tags of our articles? 

### ISSUE THREAD

**Issue by liuxingYuuu** [DTStack/UED#2]
> **Everytime before we publish the aticles, we usually give some tags to them,( like `JS` 、`react`、`前端` and so on) but now we can't find a callBack to get these tags, so we must find some way to deal with it.**

But maybe we can: 
- Give up the tag feature;
- Just use the data which we can get from our own dataBase; 
- Use the crawlers to try to get the tag-data;
- Write the dead data in our own database;

**Comment by mumiao** [comment]
support tag feature
